API_ID: 29124922
API_HASH: 59fad73fd7de8140c4966e9300fef085
BOT_TOKEN: 8161625128:AAH-s6KpjGEWWwMxaZofy2eik2nJtx4yNCw

MONGO_URL: mongodb+srv://ottsonlywork:Aditi733202@cluster0.nhutwmd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

REDIS_URI: redis://:Aditi3232@localhost:6379
REDIS_PORT: 6379
REDIS_PASS: Aditi3232

SESSION_API_ID: 29124922
SESSION_API_HASH: 59fad73fd7de8140c4966e9300fef085
SESSION_STRING: AQG8aToALrw4xQ6U8oCdFXevy0KOF64sp_P0ytPiAokM8JOX3Ym9Th3XJ0Ha2mAMS0t9ZB6SICfWrdCH4PEtvdOPFD5CHSFPDsCRm3xMVn7Nnq_1-LYuGgg5InpVefIlkHnXDqFHNR4-ruqgmlNeTi83nJFw3Yz93Kw8uxfT7M1I2A35lRtNltI1zOhV1Y2hmJhDjXDDbgaU-8SZp-PU1Tm22VR58I2aSNU77wr8s4b-DPi731YxQKx3B2IgU3jzfZJyjd_22NcsZ8OdHQdGlV6FdZUFnMJnA0FWpnrn1uBLRdK3j_TZKtpwkhDU-uaj-qOQuczulk2kkQOJawqoPuxOEetSvgAAAAGo0wuWAA

ADMINS:
  - 7127370646

OWNER: 7127370646

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg

SUPPORT_CHAT: -4863193854
LOG_CHAT: -4758912978

HANDLERS:
  - "."
  - "!"
  - "/"
  - "?"

